accessControl:
  userfile: /octoprint/octoprint/users.yaml
api:
  key: 49E63420F8204071BF91283DB2441D20
appearance:
  name: Miniprintbox
  showFahrenheitAlso: true
plugins:
  Octoslack:
    _config_version: 2
    connection_method: ROCKETCHAT
    discord_config:
      alternate_username: Frank's 3D Print Updates
      webhook_urls: https://discord.com/api/webhooks/1101092273640452109/CL0BtdcOytwWreO2y1mbZW-RCEnkLKKLbNaWVGJ6SfdLxDoGpdXB3-9OUwvGzMwWAZ7f
    gcode_events: '[]'
    rocketchat_config:
      channel: Prints_In_Orbit
      password: password
      server_url: https://rocket.example.com
      username: example@example.com
    s3_config:
      file_expire_days: '60'
    snapshot_upload_method: ROCKETCHAT
    supported_events:
      Connected:
        PushoverPriority: |2

          0
        PushoverSound: |2

          pushover
      Connecting:
        PushoverPriority: |2

          0
        PushoverSound: |2

          pushover
      Disconnected:
        PushoverPriority: |2

          0
        PushoverSound: |2

          pushover
      Disconnecting:
        PushoverPriority: |2

          0
        PushoverSound: |2

          pushover
      Error:
        PushoverPriority: |2

          0
        PushoverSound: |2

          pushover
      Heartbeat:
        PushoverPriority: |2

          0
        PushoverSound: |2

          pushover
      MetadataAnalysisFinished:
        PushoverPriority: |2

          0
        PushoverSound: |2

          pushover
      MetadataAnalysisStarted:
        PushoverPriority: |2

          0
        PushoverSound: |2

          pushover
      MovieDone:
        PushoverPriority: |2

          0
        PushoverSound: |2

          pushover
      MovieFailed:
        PushoverPriority: |2

          0
        PushoverSound: |2

          pushover
      MovieRendering:
        PushoverPriority: |2

          0
        PushoverSound: |2

          pushover
      PrintCancelled:
        PushoverPriority: |2

          0
        PushoverSound: |2

          pushover
      PrintCancelling:
        PushoverPriority: |2

          0
        PushoverSound: |2

          pushover
      PrintDone:
        PushoverPriority: |2

          0
        PushoverSound: |2

          pushover
      PrintFailed:
        PushoverPriority: |2

          0
        PushoverSound: |2

          pushover
      PrintPaused:
        PushoverPriority: |2

          0
        PushoverSound: |2

          pushover
      PrintResumed:
        PushoverPriority: |2

          0
        PushoverSound: |2

          pushover
      PrintStarted:
        PushoverPriority: |2

          0
        PushoverSound: |2

          pushover
      Progress:
        Enabled: true
        IntervalPct: '10'
        PushoverPriority: |2

          0
        PushoverSound: |2

          pushover
      Shutdown:
        PushoverPriority: |2

          0
        PushoverSound: |2

          pushover
      Startup:
        PushoverPriority: |2

          0
        PushoverSound: |2

          pushover
    timezone: America/Los_Angeles
  action_command_notification:
    enable_popups: true
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1670938200
      _important:
        read_until: 1521111600
      _octopi:
        read_until: 1670518800
      _plugins:
        read_until: 1672293600
      _releases:
        read_until: 1666085100
    enabled_channels:
    - _important
  bedlevelvisualizer:
    _config_version: 1
  classicwebcam:
    _config_version: 1
    snapshot: http://miniprintbox.local:8080/?action=snapshot
    stream: /webcam/?action=stream
  dashboard:
    ETAShowSeconds: true
    _config_version: 2
    clearOn_Feedrate: '2'
    clearOn_Filament: '2'
    clearOn_LayerGraph: '1'
    clearOn_PrintThumbnail: '2'
    clearOn_PrinterMessage: '2'
    commandWidgetArray:
    - command: echo "47.6" | bc
      enabled: false
      icon: command-icon.png
      interval: '60'
      name: Simulated Chamber
      type: 3/4
    fullscreenUseThemeColors: true
  discovery:
    upnpUuid: cc7fedc4-bf52-495e-9e91-f95963a7159a
  errortracking:
    unique_id: e6cc1d06-7a44-48c9-a96e-6468936a514a
  gcodeviewer:
    _config_version: 1
  obico:
    auth_token: 75f8a0102e7fb44e6a0c
    endpoint_prefix: http://miniprintbox.local:3334
    sentry_opt: in
  softwareupdate:
    _config_version: 9
  tracking:
    enabled: false
    unique_id: 64d345d2-4502-4579-8bc4-512dbf7782d7
  uicustomizer:
    gcodeZoom: 1
    mainTabs:
    - - control_link
      - true
      - false
      - fas fa-expand-arrows-alt
      - true
      - false
    - - temp_link
      - true
      - false
      - fas fa-thermometer-half
      - true
      - false
    - - timelapse_link
      - true
      - false
      - fas fa-film
      - true
      - false
    - - term_link
      - true
      - false
      - fas fa-terminal
      - true
      - false
    - - gcode_link
      - true
      - false
      - fab fa-codepen
      - true
      - false
    - - tab_plugin_dashboard_link
      - true
      - false
      - false
      - textOnly
      - '#000000'
    - - tab_plugin_bedlevelvisualizer_link
      - true
      - false
      - false
      - textOnly
      - '#000000'
    rows:
    - _00#connection_wrapper: true
      _01#state_wrapper: true
      _02#sidebar_plugin_firmware_check_warning_wrapper: false
      _03#sidebar_plugin_firmware_check_info_wrapper: false
    - _00div.UICmainTabs: true
      _01#files_wrapper: true
    - _00#UICGcodeVWidget: true
      _01#UICTempWidget: true
      _02#UICWebCamWidget: true
      _03#sidebar_plugin_action_command_notification_wrapper: true
    theme: darkgreen
    themeLocal: false
    themeVersion: 0.2.9.8
    topIconSort:
    - navbar_plugin_action_command_prompt
    - navbar_plugin_logging_seriallog
    - navbar_plugin_logging_plugintimingslog
    widths:
    - '3'
    - '6'
    - '3'
  virtual_printer:
    _config_version: 1
printerProfiles:
  default: _default
serial:
  autoconnect: true
server:
  commands:
    serverRestartCommand: s6-svc -r /var/run/s6/services/octoprint
  firstRun: false
  onlineCheck:
    enabled: true
  pluginBlacklist:
    enabled: true
  secretKey: vdYz166In0DUGetwR4FtxTuTI4ujJzC1
temperature:
  profiles:
  - bed: 100
    chamber: null
    extruder: 210
    name: ABS
  - bed: 60
    chamber: null
    extruder: 180
    name: PLA
webcam:
  bitrate: 15000k
  ffmpeg: /usr/bin/ffmpeg
  ffmpegThreads: 10
  ffmpegVideoCodec: mpeg2video
