site_name: Miniprintbox
theme:
  features:
    - navigation.tracking
    - content.code.copy
    - navigation.footer

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  language: en
  logo: /images/mpb2.svg
  favicon: /images/mpb2.svg
  name: material
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      primary: light green
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: light green
      accent: light blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
repo_url: https://github.com/hentronnumerouno/miniprintbox
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Docs:
    - Introduction: index.md
    - Installation: Installation.md
    - Configuration: Configuration.md
    - Uninstallation: Uninstallation.md
    - Troubleshooting: Troubleshooting.md
copyright: Made by Humans, in the USA 🇺🇸
